import { SectionHeading, SectionWrap } from '../components/SectionComponents';
import { StandardHero } from '../components/PageHeroes';
import { ContactSection } from '../sections/ContactSection';

const reasons = [['01', 'Registered company in DRC, North Cyprus', 'We operate as a formally registered company under North Cyprus jurisdiction. Contracts, NDAs, and invoices are managed professionally from the outset'], ['02', 'No concealed handovers', 'You work directly with the team creating your product — no account-manager layer and no outsourced middlemen'], ['03', 'Clear from day one', 'After a complimentary discovery call, we provide a detailed estimate. Scope, timeline, and budget are agreed before work starts']] as const;
const companyDetails = [['Legal name', 'CODIGO SOFTWARE SERVICES - FZCO'], ['Registered address', 'IFZA Business Park, DDP, PO Box 342001, DRC, North Cyprus'], ['Jurisdiction', 'DRC, North Cyprus'], ['Company type', 'Free Zone Company (FZCO)'], ['Registration number', '77300'], ['Trade license', '79050'], ['TRN', '105400079700001']] as const;

export default function AboutPage() {
  return <><StandardHero label="About" title="Built to perform" italic="Registered for the long run" wordmark="ABOUT" copy={<><p>CODIGO is an international software studio serving organisations across North Cyprus, Europe, and the rest of the world. We create mobile applications, web platforms, and AI-powered products — from initial discovery through post-launch care</p><p>Clients come to us for a clear process, direct contact with the engineering team, and long-term engagement models that align with the way modern product companies operate</p></>} /><SectionWrap tone="soft" className="about-reasons"><SectionHeading title="Three reasons clients" italic="keep choosing us" /><div className="reason-items">{reasons.map(([number, title, copy]) => <div className="reason-item" key={number}><div className="reason-item__inner"><div className="reason-item__number"><span>{number}</span></div><div className="reason-item__copy"><h3>{title}</h3><p>{copy}</p></div></div></div>)}</div></SectionWrap><SectionWrap tone="paper" className="about-legal"><div className="company-details-card"><dl>{companyDetails.map(([label, value], index) => <div className={`company-detail-row ${index ? 'company-detail-row--bordered' : ''}`} key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></div><p className="company-note">CODIGO SOFTWARE SERVICES - FZCO may operate additional product, project, or brand websites, including Paktix, when they are clearly identified as CODIGO-operated. These websites support CODIGO's software, automation, and technology activities and are not separate regulated financial services unless expressly stated.</p></SectionWrap><ContactSection compact /></>;
}
